# Generated by Django 4.2.1 on 2023-05-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=20)),
                ('secondName', models.CharField(default=None, max_length=20)),
                ('lastName', models.CharField(max_length=15)),
            ],
            options={
                'default_related_name': 'base_users',
            },
        ),
        migrations.CreateModel(
            name='AdminLibrary',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser')),
                ('last_report', models.DateField()),
            ],
            options={
                'default_related_name': 'admin_library_users',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser')),
                ('carrer', models.CharField(max_length=20)),
                ('has_rented', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'students_users',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseuser')),
                ('university_department', models.CharField(max_length=20)),
                ('has_rented', models.BooleanField(default=False)),
            ],
            options={
                'default_related_name': 'teachers_users',
            },
            bases=('users.baseuser',),
        ),
    ]
